# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_save(object):
    def setupUi(self, save):
        save.setObjectName("save")
        save.resize(1612, 1030)
        self.TitleLabel = TitleLabel(save)
        self.TitleLabel.setGeometry(QtCore.QRect(40, 50, 421, 38))
        self.TitleLabel.setObjectName("TitleLabel")
        self.TableWidget = TableWidget(save)
        self.TableWidget.setGeometry(QtCore.QRect(40, 170, 1491, 791))
        self.TableWidget.setObjectName("TableWidget")
        self.TableWidget.setColumnCount(8)
        self.TableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(7, item)
        self.PrimaryPushButton = PrimaryPushButton(save)
        self.PrimaryPushButton.setGeometry(QtCore.QRect(40, 110, 153, 32))
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")

        self.retranslateUi(save)
        QtCore.QMetaObject.connectSlotsByName(save)

    def retranslateUi(self, save):
        _translate = QtCore.QCoreApplication.translate
        save.setWindowTitle(_translate("save", "Form"))
        self.TitleLabel.setText(_translate("save", "识别结果与保存"))
        item = self.TableWidget.verticalHeaderItem(0)
        item.setText(_translate("save", "1"))
        item = self.TableWidget.verticalHeaderItem(1)
        item.setText(_translate("save", "2"))
        item = self.TableWidget.verticalHeaderItem(2)
        item.setText(_translate("save", "2"))
        item = self.TableWidget.verticalHeaderItem(3)
        item.setText(_translate("save", "3"))
        item = self.TableWidget.verticalHeaderItem(4)
        item.setText(_translate("save", "5"))
        item = self.TableWidget.horizontalHeaderItem(0)
        item.setText(_translate("save", "鱼群x"))
        item = self.TableWidget.horizontalHeaderItem(1)
        item.setText(_translate("save", "鱼群y"))
        item = self.TableWidget.horizontalHeaderItem(2)
        item.setText(_translate("save", "瞬时速度"))
        item = self.TableWidget.horizontalHeaderItem(3)
        item.setText(_translate("save", "平均速度"))
        item = self.TableWidget.horizontalHeaderItem(4)
        item.setText(_translate("save", "鱼群分散度"))
        item = self.TableWidget.horizontalHeaderItem(5)
        item.setText(_translate("save", "瞬时最远距离"))
        item = self.TableWidget.horizontalHeaderItem(6)
        item.setText(_translate("save", "瞬时最近距离"))
        item = self.TableWidget.horizontalHeaderItem(7)
        item.setText(_translate("save", "平均距离"))
        self.PrimaryPushButton.setText(_translate("save", "保存到excel"))
from qfluentwidgets import PrimaryPushButton, TableWidget, TitleLabel
