# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_show(object):
    def setupUi(self, show):
        show.setObjectName("show")
        show.resize(1518, 991)
        self.gridLayout = QtWidgets.QGridLayout(show)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(show)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(53, 53, 53);\n"
"color: rgb(255, 255, 255);")
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(show)
        QtCore.QMetaObject.connectSlotsByName(show)

    def retranslateUi(self, show):
        _translate = QtCore.QCoreApplication.translate
        show.setWindowTitle(_translate("show", "Form"))
        self.label.setText(_translate("show", "鱼群识别展示区域"))
